class Team < ActiveRecord::Base
  has_many :fans, class_name: "User", foreign_key: :favorite_team_id

  validates :location, :name, presence: true

  def twitter_handle
    case self.name
    when "Bills"
      handle = "buffalobills"
    when "Dolphins"
      handle = "MiamiDolphins"
    when "Patriots"
      handle = "Patriots"
    when "Jets"
      handle = "nyjets"
    when "Ravens"
      handle = "Ravens"
    when "Bengals"
      handle = "Bengals"
    when "Browns"
      handle = "Browns"
    when "Steelers"
      handle = "steelers"
    when "Texans"
      handle = "HoustonTexans"
    when "Colts"
      handle = "Colts"
    when "Jaguars"
      handle = "Jaguars"
    when "Titans"
      handle = "Titans"
    when "Broncos"
      handle = "Broncos"
    when "Chiefs"
      handle = "Chiefs"
    when "Raiders"
      handle = "RAIDERS"
    when "Chargers"
      handle = "Chargers"
    when "Cowboys"
      handle = "dallascowboys"
    when "Giants"
      handle = "Giants"
    when "Eagles"
      handle = "Eagles"
    when "Redskins"
      handle = "Redskins"
    when "Bears"
      handle = "ChicagoBears"
    when "Lions"
      handle = "Lions"
    when "Packers"
      handle = "packers"
    when "Vikings"
      handle = "Vikings"
    when "Falcons"
      handle = "AtlantaFalcons"
    when "Panthers"
      handle = "Panthers"
    when "Saints"
      handle = "Saints"
    when "Buccaneers"
      handle = "TBBuccaneers"
    when "Cardinals"
      handle = "AZCardinals"
    when "Rams"
      handle = "RamsNFL"
    when "49ers"
      handle = "49ers"
    when "Seahawks"
      handle = "Seahawks"
    else
      handle = "NFL"
    end
    "https://twitter.com/#{handle}"
  end
end
